// Common or dashboard
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_SIDEBAR_OPEN = "SET_IS_SIDEBAR_OPEN";

export const LOGIN_REQUEST = "LOGIN_REQUEST"; // Add this line
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Customer 
export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const SET_ALL_CUSTOMER = "SET_ALL_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const BAN_CUSTOMER = "BAN_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

// actionTypes.js

// Category actions
export const GET_CATEGORIES = "GET_CATEGORIES"; // Fetch all categories
export const SET_CATEGORIES = "SET_CATEGORIES"; // Store fetched categories
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID"; // Fetch a specific category
export const SET_CATEGORY = "SET_CATEGORY"; // Store a specific category
export const CREATE_CATEGORY = "CREATE_CATEGORY"; // Create a new category
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"; // Successful category creation
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE"; // Failed category creation
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"; // Update an existing category
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"; // Successful category update
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE"; // Failed category update
export const DELETE_CATEGORY = "DELETE_CATEGORY"; // Delete a category
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"; // Successful category deletion
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE"; // Failed category deletion

//Banners
export const GET_BANNERS = "GET_BANNERS";
export const SET_BANNERS = "SET_BANNERS";
export const GET_BANNER_BY_ID = "GET_BANNER_BY_ID";
export const SET_BANNER = "SET_BANNER";
export const CREATE_BANNER = "CREATE_BANNER";
export const CREATE_BANNER_SUCCESS = "CREATE_BANNER_SUCCESS";
export const CREATE_BANNER_FAILURE = "CREATE_BANNER_FAILURE";
export const UPDATE_BANNER = "UPDATE_BANNER";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAILURE = "UPDATE_BANNER_FAILURE";
export const DELETE_BANNER = "DELETE_BANNER";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAILURE = "DELETE_BANNER_FAILURE";

//Products
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const SET_PRODUCT = "SET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";


// Partner
export const GET_PARTNERS = "GET_PARTNERS";
export const SET_PARTNERS = "SET_PARTNERS";
export const GET_PARTNER_BY_ID = "GET_PARTNER_BY_ID";
export const SET_PARTNER = "SET_PARTNER";
export const CREATE_PARTNER = "CREATE_PARTNER";
export const CREATE_PARTNER_SUCCESS = "CREATE_PARTNER_SUCCESS";
export const CREATE_PARTNER_FAILURE = "CREATE_PARTNER_FAILURE";
export const UPDATE_PARTNER = "UPDATE_PARTNER";
export const UPDATE_PARTNER_SUCCESS = "UPDATE_PARTNER_SUCCESS";
export const UPDATE_PARTNER_FAILURE = "UPDATE_PARTNER_FAILURE";

export const UPDATE_PARTNER_BANK_DETAILS = "UPDATE_PARTNER_BANK_DETAILS";
export const UPDATE_PARTNER_BANK_DETAILS_SUCCESS = "UPDATE_PARTNER_BANK_DETAILS_SUCCESS";
export const UPDATE_PARTNER_BANK_DETAILS_FAILURE = "UPDATE_PARTNER_BANK_DETAILS_FAILURE";

export const UPDATE_PARTNER_BASIC_DETAILS = "UPDATE_PARTNER_BASIC_DETAILS";
export const UPDATE_PARTNER_BASIC_DETAILS_SUCCESS = "UPDATE_PARTNER_BASIC_DETAILS_SUCCESS";
export const UPDATE_PARTNER_BASIC_DETAILS_FAILURE = "UPDATE_PARTNER_BASIC_DETAILS_FAILURE";

export const UPDATE_PARTNER_GST_DETAILS = "UPDATE_PARTNER_GST_DETAILS";
export const UPDATE_PARTNER_GST_DETAILS_SUCCESS = "UPDATE_PARTNER_GST_DETAILS_SUCCESS";
export const UPDATE_PARTNER_GST_DETAILS_FAILURE = "UPDATE_PARTNER_GST_DETAILS_FAILURE";

export const UPDATE_PARTNER_FIRM_DETAILS = "UPDATE_PARTNER_FIRM_DETAILS";
export const UPDATE_PARTNER_FIRM_DETAILS_SUCCESS = "UPDATE_PARTNER_FIRM_DETAILS_SUCCESS";
export const UPDATE_PARTNER_FIRM_DETAILS_FAILURE = "UPDATE_PARTNER_FIRM_DETAILS_FAILURE";

export const UPDATE_PARTNER_DETAILS = "UPDATE_PARTNER_DETAILS";
export const UPDATE_PARTNER_DETAILS_SUCCESS = "UPDATE_PARTNER_DETAILS_SUCCESS";
export const UPDATE_PARTNER_DETAILS_FAILURE = "UPDATE_PARTNER_DETAILS_FAILURE";

export const DELETE_PARTNER = "DELETE_PARTNER";
export const DELETE_PARTNER_SUCCESS = "DELETE_PARTNER_SUCCESS";
export const DELETE_PARTNER_FAILURE = "DELETE_PARTNER_FAILURE";


//Tags
export const GET_TAGS = "GET_TAGS";
export const SET_TAGS = "SET_TAGS";
export const GET_TAG_BY_ID = "GET_TAG_BY_ID";
export const SET_TAG = "SET_TAG";
export const CREATE_TAG = "CREATE_TAG";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_FAILURE = "CREATE_TAG_FAILURE";
export const UPDATE_TAG = "UPDATE_TAG";
export const UPDATE_TAG_SUCCESS = "UPDATE_TAG_SUCCESS";
export const UPDATE_TAG_FAILURE = "UPDATE_TAG_FAILURE";
export const DELETE_TAG = "DELETE_TAG";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
export const DELETE_TAG_FAILURE = "DELETE_TAG_FAILURE";


//Dashboard
export const GET_DASHBOARD = "GET_DASHBOARD";
export const SET_DASHBOARD = "SET_DASHBOARD";
